# Syncs custom UI components from pi-webby-exp (reference) to pi-desktop-app
# Run after modifying any custom component in webby to keep desktop in sync.
# Standard shadcn/ui components (generated by `shadcn add`) are NOT synced —
# regenerate them independently with `pnpm shadcn add <component>`.

$customComponents = @(
    "bubble.tsx",
    "message.tsx",
    "message-scroller.tsx",
    "attachment.tsx",
    "marker.tsx",
    "empty.tsx",
    "spinner.tsx",
    "item.tsx",
    "button-group.tsx",
    "input-group.tsx"
)

$sourceDir = "pi-webby-exp/src/components/ui"
$destDir = "pi-desktop-app/src/components/ui"

foreach ($file in $customComponents) {
    $src = Join-Path $sourceDir $file
    $dst = Join-Path $destDir $file
    if (Test-Path $src) {
        Copy-Item $src $dst -Force
        Write-Host "  synced: $file"
    } else {
        Write-Host "  SKIP (not found): $file" -ForegroundColor Yellow
    }
}

Write-Host "`nDone. $($customComponents.Count) components synced."
