#!/usr/bin/env bash
# Syncs custom UI components from pi-webby-exp (reference) to pi-desktop-app.
# Run after modifying any custom component in webby to keep desktop in sync.
# Standard shadcn/ui components (generated by `shadcn add`) are NOT synced —
# regenerate them independently with `pnpm shadcn add <component>`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SOURCE_DIR="$SCRIPT_DIR/pi-webby-exp/src/components/ui"
DEST_DIR="$SCRIPT_DIR/pi-desktop-app/src/components/ui"

COMPONENTS=(
    "bubble.tsx"
    "message.tsx"
    "message-scroller.tsx"
    "attachment.tsx"
    "marker.tsx"
    "empty.tsx"
    "spinner.tsx"
    "item.tsx"
    "button-group.tsx"
    "input-group.tsx"
)

for file in "${COMPONENTS[@]}"; do
    src="$SOURCE_DIR/$file"
    dst="$DEST_DIR/$file"
    if [[ -f "$src" ]]; then
        cp "$src" "$dst"
        echo "  synced: $file"
    else
        echo "  SKIP (not found): $file" >&2
    fi
done

echo ""
echo "Done. ${#COMPONENTS[@]} components synced."
